### PR TITLE
Update GitHub Action to test both IC & IU

### PR DESCRIPTION
**Pull request by ChrisCarini**
This will test both IJ Community, and IJ Ultimate - other IDEs can also be tested if desired, see here for docs: https://github.com/ChrisCarini/intellij-platform-plugin-verifier-action#ide-versions

### CODE REVIEW

**Comment by gilday** [comment]
🤔 I'm not sure why the "Build and Test" action didn't run on this PR. I added some more trigger events to see if that helps.

Thanks for the contribution!

**Comment by ChrisCarini** [comment]
Hi @gilday - no problem! Happy to help!

This is **totally** a guess, but maybe "build & test" didn't run because this is just a workflow file change?

**Comment by gilday** [comment]
I _think_ it was because `pull_request` was missing from the list of trigger events. Before adding that event, the list only contained the `push` event. I see you made the change with the GitHub editor - I'm not sure if that triggers the `push` event, because it's possible there is no `git push`. Not sure - I'll find out on the next PR that gets opened!

**Comment by ChrisCarini** [comment]
Ah, that would make sense to me!

**Pull request merged**
