### PR TITLE
Added compatibility to IDEA 2019.3

### PR DESCRIPTION
**Pull request by kannicht**
Just added compability to version 2019.3 to have the plugin still working.

### CODE REVIEW

**Comment by fehbari** [comment]
I just tried `runIde` this and it seems to work fine!

A couple things though:

----------

Shouldn't plugin version be bumped in `build.gradle.kts`?

```
version = "1.0.5"
```

(or maybe not if plugin author will update it himself before publishing)

 -----------
I also noticed `build` and `buildPlugin` both fail with 

```
com.intellij.diagnostic.PluginException: Failed to find expected "Light" theme
```

 because `lafManager.getInstalledLookAndFeels()` in `DarkModeSync.java:45` returns an empty array at build-time.

I tried replacing that portion of the code with just

```
  private final LookAndFeelInfo lightLaf = new IntelliJLookAndFeelInfo();
```

instead of searching for "Light" theme in the array at runtime. Plugin functionality seems to work the same (2019.3 and macOS Catalina), but `build` tasks now work.

Do we know why we search the array instead of using `IntelliJLookAndFeelInfo`? I haven't tried this with 2019.2 so perhaps it's for compatibility reasons, but I'll give it a shot. cc @gilday 

**Update**: `IntelliJLookAndFeelInfo()` seems to work fine as far back as 2019.1.4. I'll open a different PR suggesting this change. See #6

**Review by fehbari — APPROVED** [review]

**Comment by gilday** [comment]
@fehbari re:

> Shouldn't plugin version be bumped in build.gradle.kts?

Merges to the `master` branch will deploy the plugin to the JetBrains plugin repository, so I'm going to retarget PRs to the `develop` branch so that I can bump version and release after batching some changes together

**Comment by gilday** [comment]
@kannicht there are two changes in this PR I'd like to keep separate

1. Compatibility with 2019.3
1. Preferences UI for themes

The first change "Compatibility with 2019.3" is a relatively small change like you had in #4. I'd like to get this shipped quickly now that 2019.3 is out, so I plan to push this change and release it in 1.0.5 along with #6. 

The second change "Preferences UI for Themes" address #2. Consider refocusing this PR to address #2 since the 2019.3 will be fixed upstream imminently.

**Comment by kannicht** [comment]
Thank you for coming back to the PR. I'd suggest to close this PR for now as you already implemented the changes to support the latest IDEA versions. 

btw: this was my first PR so I'm sorry for any trouble I caused on this matter. :)

**Comment by gilday** [comment]
@kannicht no trouble, I appreciate the PR (and congrats on your first PR)! Please feel free to open another if you finish the settings for choosing themes see (#2 )

**Pull request closed without merging**
